name: Tests on PR
on:
  pull_request:
    branches:
      - develop
      - main
jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
    - name: Copia repositorio
      uses: actions/checkout@v2
    - name: Construye imagen
      run: docker build --tag islasgeci/weak_inspector .
    - name: Verifica el formato
      run: docker run islasgeci/weak_inspector make check
    - name: Corre pruebas y evalúa cobertura
      run: docker run islasgeci/weak_inspector make coverage
    - name: Evalúa resistencia a mutaciones
      run: docker run islasgeci/weak_inspector make mutants
      